library(shiny)
library(tidyverse)

fdata = readxl::read_excel("ardd_fatalities_jun2022.xlsx",
                           sheet = 2,
                           skip = 4,
                           na = c("", "-9"),
                           guess_max = 1e6
                          ) %>%
  janitor::clean_names() %>%
  mutate(
    month_name = factor(month.abb[month], levels = month.abb)
  )

# Define UI for application that draws a 
ui <- fluidPage(
  
  titlePanel("Fatalities"),
  
  sidebarLayout(
    sidebarPanel(
      # Use input$inputId to access variables in server section
      selectInput(inputId = "year_selection",
                  label = "Select year: ",
                  choices = 1989:2021,
                  selected = 2019,
                  multiple = TRUE # allow to select multiple inputs
                  )
    ),
    
    mainPanel(
      plotOutput("fatalitiesPlot"),
      verbatimTextOutput("chisq_test")
    )
  )
)

# Define server logic required to draw a
server <- function(input, output) {
  
  final_data = reactive({
    fdata %>%
      filter(year %in% input$year_selection) # filter all years that is selected
  })
  
  output$fatalitiesPlot <- renderPlot({
    
    col_title = paste(
      paste(
        input$year_selection, 
        collapse = ", "
        ),
      "road fatalities by months")
    
    final_data() %>%
      ggplot() +
      aes(x = month_name, fill = factor(year)) + # column n is generated by count()
      geom_bar() +
      labs(title = col_title, x = "month", fill = "year")
    
  })
  
  output$chisq_test = renderPrint({
    
    final_data() %>%
      pull(month_name) %>%
      table() %>%
      chisq.test()
    
  })
}

# Run the application
shinyApp(ui = ui, server = server)